### ISSUE TITLE
Bad line

### ISSUE THREAD

**Issue by yssrku** [AnTheMaker/GoodBots#1]
Hi,

I see there's a bad line in all.ips, you might need some error handling when you got bad response from upstream
https://github.com/AnTheMaker/GoodBots/blob/730c4e256ee32d0aab3a535b450a6161fa6f53a5/all.ips#L9790

**Comment by AnTheMaker** [comment]
Hi there!
Thanks for making me aware of this!
This should be fixed in a707e1cd0babff350d7fa95eaf94b5746de2f412
I've added a validation step which validates all IP ranges and removes invalid ones!
